name: Solar Sysem Workflow

on:
  workflow_dispatch:
  push:
    branches:
        - main
        - feature/*

env:
   MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
   MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
   MONGO_PASSWORD:  ${{secrets.MONGO_PASSWORD}}     

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [19, 20]
        operating_system: [ubuntu-latest] #macos-latest
        exclude:
         - nodejs_version: 20
           operating_system: ubuntu-latest

    runs-on: ${{matrix.operating_system}}
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Setup NodeJS version - ${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
              node-version: ${{matrix.nodejs_version}}
        
        - name: Cache NPM Dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashfiles('package-lock.json')}}

        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          run: npm test

        - name: Archive Test Results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Results-${{ github.run_id }}-${{ matrix.operating_system }}
            path: test-results.xml      
  
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup NodeJS version - 18
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-node-modules-${{hashfiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
            name: Code-Coverage-Results
            path: Coverage
            retention-days: 5

  docker:
    needs: [unit-testing, code-coverage ]
    name: Containerization
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: Dockerhub login
        uses: docker/login-action@v2.2.0
        with:
            username: ${{vars.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: GHCR login
        uses: docker/login-action@v2.2.0
        with:
            registry: ghcr.io
            username: ${{github.repository_owner}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker Build For Testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}

      - name: Docker Image Testing
        run: |
          docker images
          
          docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP
         
          echo Testing Image URL Using Wget
          wget -qO- http://127.0.0.1:3000/live | grep live

      - name: Docker Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
             ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
             ghcr.io/${{github.repository_owner}}/solar-system:${{github.sha}}
# Need to create an environment in the repo settings and configure protection rules for all the below 4 jobs.
  dev-deploy:
    if: contains(github.ref, 'feature/')
    name:
    runs-on: ubuntu-latest
    needs: docker
    environment:
            name: development
            url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
    outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
    steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.26.0'
            - name: Set Kubeconfig
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}
            - name: Fetch Kubernetes Cluster Details
              run: |
                kubectl version --short -o yaml
                echo ---------------------
                kubectl get nodes
            - name: Save Nginx Ingress Controller IP as a GITHUB Environment Variable
              run: |
                  echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
            - name: Replace Tokens in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE}}
                REPLICAS: ${{ vars.REPLICAS}}
                IMAGE: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}
                INGRESS_IP: ${{ env.INGRESS_IP}}
            - name: Check files
              run: |
                cat kubernetes/development/*.yaml
            - name: Create MongoDB Secret
              run: |
                kubectl -n ${{ vars.NAMESPACE}} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{ env.MONGO_URI}}
                --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME}}
                --from-literal=MONGO_PASSWORD=${{ env.MONGO_PASSWORD}}
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -
            - name: Deploy to Dev Env
              run: |
                kubectl apply -f kubernetes/development
            - name: Set App Ingress Host URL
              id: set-ingress-host-address
              run: |
                  echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE}} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT

  dev-integration-testing:
    name: Dev Integration Testing
    if: contains(github.ref, 'feature/')
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
          - name: Test URL Output using CURL and JQ
            env:
              URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL}}
            run: |
              echo $URL
              echo "---------------------------"
              curl https://$URL/live -s -k | jq -r .status | grep -i live

  prod-deploy:
    name:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: dev-integration-testing
    environment:
            name: production
            url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
    outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
    steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.26.0'
            - name: Set Kubeconfig
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}
            - name: Fetch Kubernetes Cluster Details
              run: |
                kubectl version --short -o yaml
                echo ---------------------
                kubectl get nodes
            - name: Save Nginx Ingress Controller IP as a GITHUB Environment Variable
              run: |
                  echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
            - name: Replace Tokens in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/production/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE}}
                REPLICAS: ${{ vars.REPLICAS}}
                IMAGE: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}
                INGRESS_IP: ${{ env.INGRESS_IP}}
            - name: Check files
              run: |
                cat kubernetes/production/*.yaml
            - name: Create MongoDB Secret
              run: |
                kubectl -n ${{ vars.NAMESPACE}} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{ env.MONGO_URI}}
                --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME}}
                --from-literal=MONGO_PASSWORD=${{ env.MONGO_PASSWORD}}
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -
            - name: Deploy to Prod Env
              run: |
                kubectl apply -f kubernetes/production
            - name: Set App Ingress Host URL
              id: set-ingress-host-address
              run: |
                  echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE}} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT

  prod-integration-testing:
    name: Prod Integration Testing
    if: github.ref == 'refs/heads/main'
    needs: prod-deploy
    runs-on: ubuntu-latest
    steps:
          - name: Test URL Output using CURL and JQ
            env:
              URL: ${{ needs.prod-deploy.outputs.APP_INGRESS_URL}}
            run: |
              echo $URL
              echo "---------------------------"
              curl https://$URL/live -s -k | jq -r .status | grep -i live
